### ISSUE TITLE
Unable to import module 'rotate': /var/task/bcrypt/_bcrypt.so: invalid ELF header

### ISSUE THREAD

**Issue by cwyl02** [aws-samples/aws-secrets-manager-ssh-key-rotation#1]
Hi there,

Recently we have SSH key rotation requirement to meet and we found Secrets Manager and we found this repo. First of all thanks for all the great work!

However, after I deployed the cloudformation stack and try out how things work, I see this error in Secrets Manager: 
Fail to rotate the secret "test-ssh-key" A previous rotation isn’t complete. That rotation will be reattempted.

Then I went to take a look at the lambda log and found this:

**Unable to import module 'rotate': /var/task/bcrypt/_bcrypt.so: invalid ELF header**

My environment:

OS: Mac OS high sierra 10.13.6
Python2: 
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 29 2018, 20:59:26) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin

Python3: 
Python 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin

Deployment set up:

Since I skipped deploying the EC2 cf template, I modified the secretsmanager cf template at a minimal level:

... Same as the sample seceretsmanager_rotate_ssg_keys.template

VpcConfig:
        SubnetIds:
        - subnet-1234567
        - subnet-2345678
        SecurityGroupIds:
        - sg-123 # default
        - sg-345 #  SSH

... same as the sample

I also did another experiment, if I change to use pip3 in deployer.sh, the error message thrown by lambda will change to:

**Unable to import module 'rotate': /var/task/bcrypt/_bcrypt.abi3.so: invalid ELF header**

And another modification I made is just changing the region to us-east-1, which I believe is irrelevant to this issue too.

How can I get around this? I think the lambda is not correctly built?

**Comment by cwyl02** [comment]
Update: I spun up an amazon linux 2 instance and I installed python 3.6.2 on it, then followed these 2 guides: https://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html
https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html

Now the lambda can run with no problem.

Seems like it doesn't quite like Mac OS.

**Comment by maitreya1975** [comment]
Hi York,
You are correct that the bundling must be executed for this function on an
Amazon Linux server - the reason being that it bundles native crypto
libraries used to generate key-pairs and to SSH to systems.
I'm glad it worked out for you after building it. Please let me know if you
have any other feedback. I'd also included a deployer.sh that does the
steps to package the lambda - which of course needs to be run on Amazon
Linux.
Cheers,
Maitreya.

**Comment by VladChiorean** [comment]
Hi @maitreya1975 ,

I'm running into a similar issue:

Unable to import module 'rotate': No module named '_cffi_backend'

I'm executing the commands from deployer.sh on an amazon linux 2 instance.

**Comment by maitreya1975** [comment]
Hi Vlad,
The Lambda function deployed by the CloudFormation template uses Python 3.6 as the run-time. 
The underlying OS for this is Amazon Linux and not Amazon Linux 2 as described here: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

I have two suggestions:
1. You could change your Lambda run-time version to Python 3.8 that is based on Amazon Linux 2 and test it out. 
2. You could perform your build using an Amazon Linux server and stay with the Python 3.6 run-time.
Please also confirm that the Python version on your build instance matches the run-time version exactly.
Please let me know how it goes.

**Comment by VladChiorean** [comment]
Hi Maitreya,

Yeah, the mismatch between the python versions was causing the error. It works now. Thanks for the help.
