### ISSUE TITLE
AWS Lambda removing support for Python3.6

### ISSUE THREAD

**Issue by ndkoch73** [aws-samples/aws-secrets-manager-ssh-key-rotation#3]
Hi, I am using the zipped file of this code which is being hosted this (https://s3.amazonaws.com/awsiammedia/public/sample/SecretsManagerStoreRotateSSHKeyPairs/rotate_ssh.zip) s3 bucket. I noticed that the dependency on cffi in this file is for python version 3.6 and AWS recommends that all lambdas should upgrade from 3.6 to 3.9 before august 17th. Is there anyway this code can be recompilled with python3.9 and zipped for use?

**Comment by maitreya1975** [comment]
Hi, I've built a ZIP for Python 3.9 and it is in [dist/rotate_ssh_python3.9.zip](dist/rotate_ssh_python3.9.zip). I can work on getting the public S3 bucket updated.
In parallel, you can download the [Python 3.9 ZIP](dist/rotate_ssh_python3.9.zip) file from this repo and upload it to an S3 bucket of your choice in the same AWS Region where you are deploying the Lambda function. You can then update the location in the [CloudFormation template](secretsmanager_rotate_ssh_keys_packaged.yaml), look for the line that starts with `CodeUri` and replace the value with the S3 URL to your bucket and file. 
Also, modify the Lambda Runtime version to:

```
Runtime: python3.9
```
Hope this helps.

**Comment by ndkoch73** [comment]
Thank you this certainly helps, I will store the zip file in my own bucket for now but will switch back to the public bucket once it is updated!

**Comment by maitreya1975** [comment]
The public bucket is now updated with the CloudFormation template and ZIP file packaged for Python 3.9. You should now be able to follow the steps in the blog to get things deployed.
