### ISSUE TITLE
Python 3.9 is not supporting cryptography package 

### ISSUE THREAD

**Issue by Taran8892** [aws-samples/aws-secrets-manager-ssh-key-rotation#4]
When migrating to python runtime 3.9 in lambda function and using the packages from rotate_ssh_python3.9.zip, function throws the below error when invoked.

[ERROR] Runtime.ImportModuleError: Unable to import module 'rotate': No module named 'cryptography'

**Comment by maitreya1975** [comment]
Hi @Taran8892 , I just tested by deploying the file [rotate_ssh_python3.9.zip](https://github.com/aws-samples/aws-secrets-manager-ssh-key-rotation/blob/master/dist/rotate_ssh_python3.9.zip) to a Lambda function using the Python 3.9 runtime and I was able to invoke the function and rotate a secret. Could you describe how you are changing the runtime? Are you using the CloudFormation template  [secretsmanager_rotate_ssh_keys_packaged.yaml](https://github.com/aws-samples/aws-secrets-manager-ssh-key-rotation/blob/master/secretsmanager_rotate_ssh_keys_packaged.yaml) to deploy your function? This template uses a ZIP file stored on S3 but the content of the ZIP file is the same as 'rotate_ssh_python3.9.zip'.

**Comment by Taran8892** [comment]
Hi, we were using the packages by storing it in lambda layers. After putting all the packages under folder named python and creating a lambda layer it worked.
Thanks.
